# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/misile/chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/misile/chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/misile/chess/CMakeFiles /home/misile/chess//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/misile/chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

cli/ConsoleGame.o: cli/ConsoleGame.c.o
.PHONY : cli/ConsoleGame.o

# target to build an object file
cli/ConsoleGame.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cli/ConsoleGame.c.o
.PHONY : cli/ConsoleGame.c.o

cli/ConsoleGame.i: cli/ConsoleGame.c.i
.PHONY : cli/ConsoleGame.i

# target to preprocess a source file
cli/ConsoleGame.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cli/ConsoleGame.c.i
.PHONY : cli/ConsoleGame.c.i

cli/ConsoleGame.s: cli/ConsoleGame.c.s
.PHONY : cli/ConsoleGame.s

# target to generate assembly for a file
cli/ConsoleGame.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cli/ConsoleGame.c.s
.PHONY : cli/ConsoleGame.c.s

cli/Parser.o: cli/Parser.c.o
.PHONY : cli/Parser.o

# target to build an object file
cli/Parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cli/Parser.c.o
.PHONY : cli/Parser.c.o

cli/Parser.i: cli/Parser.c.i
.PHONY : cli/Parser.i

# target to preprocess a source file
cli/Parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cli/Parser.c.i
.PHONY : cli/Parser.c.i

cli/Parser.s: cli/Parser.c.s
.PHONY : cli/Parser.s

# target to generate assembly for a file
cli/Parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cli/Parser.c.s
.PHONY : cli/Parser.c.s

game/ArrayList.o: game/ArrayList.c.o
.PHONY : game/ArrayList.o

# target to build an object file
game/ArrayList.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/ArrayList.c.o
.PHONY : game/ArrayList.c.o

game/ArrayList.i: game/ArrayList.c.i
.PHONY : game/ArrayList.i

# target to preprocess a source file
game/ArrayList.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/ArrayList.c.i
.PHONY : game/ArrayList.c.i

game/ArrayList.s: game/ArrayList.c.s
.PHONY : game/ArrayList.s

# target to generate assembly for a file
game/ArrayList.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/ArrayList.c.s
.PHONY : game/ArrayList.c.s

game/Game.o: game/Game.c.o
.PHONY : game/Game.o

# target to build an object file
game/Game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/Game.c.o
.PHONY : game/Game.c.o

game/Game.i: game/Game.c.i
.PHONY : game/Game.i

# target to preprocess a source file
game/Game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/Game.c.i
.PHONY : game/Game.c.i

game/Game.s: game/Game.c.s
.PHONY : game/Game.s

# target to generate assembly for a file
game/Game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/Game.c.s
.PHONY : game/Game.c.s

game/GameHandler.o: game/GameHandler.c.o
.PHONY : game/GameHandler.o

# target to build an object file
game/GameHandler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/GameHandler.c.o
.PHONY : game/GameHandler.c.o

game/GameHandler.i: game/GameHandler.c.i
.PHONY : game/GameHandler.i

# target to preprocess a source file
game/GameHandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/GameHandler.c.i
.PHONY : game/GameHandler.c.i

game/GameHandler.s: game/GameHandler.c.s
.PHONY : game/GameHandler.s

# target to generate assembly for a file
game/GameHandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/GameHandler.c.s
.PHONY : game/GameHandler.c.s

game/Minimax.o: game/Minimax.c.o
.PHONY : game/Minimax.o

# target to build an object file
game/Minimax.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/Minimax.c.o
.PHONY : game/Minimax.c.o

game/Minimax.i: game/Minimax.c.i
.PHONY : game/Minimax.i

# target to preprocess a source file
game/Minimax.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/Minimax.c.i
.PHONY : game/Minimax.c.i

game/Minimax.s: game/Minimax.c.s
.PHONY : game/Minimax.s

# target to generate assembly for a file
game/Minimax.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/game/Minimax.c.s
.PHONY : game/Minimax.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... cli/ConsoleGame.o"
	@echo "... cli/ConsoleGame.i"
	@echo "... cli/ConsoleGame.s"
	@echo "... cli/Parser.o"
	@echo "... cli/Parser.i"
	@echo "... cli/Parser.s"
	@echo "... game/ArrayList.o"
	@echo "... game/ArrayList.i"
	@echo "... game/ArrayList.s"
	@echo "... game/Game.o"
	@echo "... game/Game.i"
	@echo "... game/Game.s"
	@echo "... game/GameHandler.o"
	@echo "... game/GameHandler.i"
	@echo "... game/GameHandler.s"
	@echo "... game/Minimax.o"
	@echo "... game/Minimax.i"
	@echo "... game/Minimax.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

